### ISSUE TITLE
Buat Tampilan Data Dosen

### ISSUE THREAD

**Issue by ahmadsofian15** [ahmadsofian15/Belajar-Github#1]
Tolong buatkan tampilan untuk menampilkan data dosen, terima kasih

**Comment by ravieazharie15** [comment]
baik saya akan segera buatkan

**Comment by ravieazharie15** [comment]
tugas sudah saya selesaikan

**Comment by ahmadsofian15** [comment]
Baik, Terima kasih sudah saya cek dan sesuai yang diinginkan
